const LOCKER_PART_TYPE = {
  BODY: 'body',
  CASE: 'case',
}

const LOCKER_PART_NAME = {
  BODY: 'body',
}

const LOCKER_PART_NAME_TO_DELETE = {
  CASE01: 'case01',
  CASE02: 'case02',
  CASE03: 'case03',
  CASE04: 'case04',
  CASE05: 'case05',
  CASE06: 'case06',
  CASE07: 'case07',
}

const LOCKER_CASE_STATE = {
  Closed: 'CLOSED',
  Opened: 'OPENED',
  Moving: 'MOVING',
}

const LOCKER_CASE_MOVE_DIRECTION = {
  In: 'IN',
  Out: 'OUT',
}

const LOCKER_CASES_ANIMATION_TYPE = {
  FromTop: 'FROM_TOP',
  FromBottom: 'FROM_BOTTOM',
  FromCenter: 'FROM_CENTER',
  FromRandom: 'FROM_RANDOM',
}

const LOCKER_CASES_RANDOM_ANIMATIONS = 'LOCKER_CASES_RANDOM_ANIMATIONS';

export {
  LOCKER_PART_TYPE,
  LOCKER_PART_NAME,
  LOCKER_PART_NAME_TO_DELETE,
  LOCKER_CASE_STATE,
  LOCKER_CASE_MOVE_DIRECTION,
  LOCKER_CASES_ANIMATION_TYPE,
  LOCKER_CASES_RANDOM_ANIMATIONS,
};
